  GNU nano 2.9.3                                     my-playbook.yaml                                               
---
  -name: My first playbook
   hosts: webservers
   become: true
   tasks:

   -name: Install apache httpd (state=present is optional)
    apt:
      name: apache2
      state: present